name: Build Wasm Engine

on:
  workflow_dispatch:

jobs:
  test:
    name: Run Property based Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4'
          cabal-version: '3.10'
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cabal/store
          key: ${{ runner.os }}-cabal-${{ hashFiles('package.yaml', '**.cabal') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Run tests
        run: |
          cabal update
          cabal test

  build-wasm:
    name: Compile Engine to WASM
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup GHC Wasm Toolchain
        run: |
          curl -L https://gitlab.haskell.org/ghc/ghc-wasm-meta/-/raw/master/bootstrap.sh | sh

      - name: Build to Wasm
        run: |
          source ~/.ghc-wasm/env
          
          wasm32-wasi-cabal update
          wasm32-wasi-cabal configure --allow-newer --ghc-options="-O2 -no-hs-main -optl-mexec-model=reactor -optl-Wl,--export=malloc -optl-Wl,--export=free -optl-Wl,--export=run_decomposition -optl-Wl,--export=free_haskell_string"
          
          wasm32-wasi-cabal build exe:Engine
          
          cp $(find dist-newstyle -name "Engine.wasm" -type f | head -n 1) ./Engine.wasm

      - name: Upload Wasm Artifact
        uses: actions/upload-artifact@v4
        with:
          name: hodge-decomposition-engine
          path: Engine.wasm
          if-no-files-found: error

      - name: Deploy Latest Release
        if: github.ref == 'refs/heads/main'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "WASM Engine Build"
          files: |
            Engine.wasm
